export const FETCH_CROPS = 'FETCH_CROPS';
export const CROPS_LOADING = 'CROPS_LOADING';
export const  CROPS_FAILED = 'CROPS_FAILED';
export const ADD_CROPS = 'ADD_CROPS';
export const CONCAT_CROPS = 'CONCAT_CROPS';
export const UPDATE_CROPS = 'UPDATE_CROPS';
export const DELETE_CROPS = 'DELETE_CROPS';

export const FETCH_DISTRICTS = 'FETCH_DISTRICTS';
export const DISTRICTS_LOADING = 'DISTRICTS_LOADING';
export const  DISTRICTS_FAILED = 'DISTRICTS_FAILED';
export const ADD_DISTRICTS = 'ADD_DISTRICTS';

export const PRODUCTION_LOADING = 'PRODUCTION_LOADING';
export const FETCH_PRODUCTION = 'FETCH_PRODUCTION';
export const  PRODUCTION_FAILED = 'PRODUCTION_FAILED';
export const ADD_PRODUCTION = 'ADD_PRODUCTION';
export const CONCAT_PRODUCTION = 'CONCAT_PRODUCTION';
export const DELETE_PRODUCTION = 'DELETE_PRODUCTION';
